// celljs-creator/assets/template/api-vue/App.vue
<template>
  <div>
  <h1>{{ message }}</h1>
  <button @click="fetchTestData">fetch test</button>
  </div>
</template>

<script setup lang="ts">
import { ContainerUtil } from '@celljs/core';
import { onMounted, ref } from 'vue';
import { HomeService } from './service';

const message = ref('Loading');
const homeService = ContainerUtil.get<HomeService>(HomeService);

const fetchTestData = () => {
  homeService.test().then(res => alert(res.data));
}

onMounted(() => {
  homeService.main().then(res => message.value = res);
})
</script>

// assets/template/api-react/app.tsx
import { ContainerUtil } from '@celljs/core';
import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { HomeService } from './service';

export const App = () => {
  const homeService = useMemo(() => {
    return ContainerUtil.get<HomeService>(HomeService);
  }, []);

  const [message, setMessage] = useState('Loading');
  useEffect(() => {
    homeService.main().then((res) => {
      setMessage(res);
    });
  }, []);

  const fetchTestData = useCallback(() => {
    homeService.test().then(res => alert(res.data));
  }, []);

  return (<div>
    <h1>{ message }</h1>
    <button onClick={ fetchTestData }>fetch test</button>
  </div>);
}
