// skills/celljs-creator/assets/template/rpc-react/app.tsx
import React, { useEffect, useState } from 'react';
import { RpcUtil } from '@celljs/rpc/lib/common';
import { WelcomeServer } from '../common/welcome-protocol';

export const App = () => {
  const [message, setMessage] = useState('Loading');
  
  useEffect(() => {
    const welcomeServer = RpcUtil.get<WelcomeServer>(WelcomeServer);
    welcomeServer.say().then((msg: string) => setMessage(msg));
  }, []);

  return (<h1>{ message }</h1>);
}

// skills/celljs-creator/assets/template/rpc-vue/App.vue
<template>
  <h1>{{ message }}</h1>
</template>

<script lang="ts" setup>
  import { RpcUtil } from '@celljs/rpc';
  import { WelcomeServer } from '../common/welcome-protocol';
  import { onMounted, ref } from 'vue';

  const message = ref('Loading');
  onMounted(() => {
    const welcomeServer = RpcUtil.get<WelcomeServer>(WelcomeServer);
      welcomeServer.say().then((msg: string) => message.value = msg);
  });
</script>
